-- ============================================================
-- DriveSelect — Supabase Schema v2.0
-- Stack: Supabase Auth + Cloudflare Pages
-- Updated: 2026-03-03
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- 1. PROFILES  (replaces old `users` table)
--    Linked to auth.users via UUID primary key.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        TEXT UNIQUE NOT NULL,
  name         TEXT NOT NULL,
  position     TEXT,
  organization TEXT,
  internal_tel TEXT,
  mobile_tel   TEXT,
  role         TEXT DEFAULT 'user' CHECK (role IN ('admin', 'staff', 'user')),
  must_change_password BOOLEAN DEFAULT FALSE,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────
-- 2. DRIVERS
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS drivers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  tel        TEXT NOT NULL,
  image      TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────
-- 3. CARS
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cars (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  type          TEXT NOT NULL,   -- 'SUV' | 'Truck' | 'Van'
  image         TEXT NOT NULL,
  license_plate TEXT,
  seats         INTEGER,
  available     BOOLEAN DEFAULT TRUE,
  driver_id     BIGINT REFERENCES drivers(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────
-- 4. BOOKINGS
--    user_id is TEXT (stores UUID from profiles.id)
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id            BIGINT REFERENCES cars(id) ON DELETE CASCADE NOT NULL,
  user_id           TEXT,                    -- UUID from profiles.id (text for flexibility)
  -- Denormalised snapshot at booking time:
  car_name          TEXT NOT NULL,
  car_license       TEXT,
  car_type          TEXT,
  user_name         TEXT NOT NULL,
  user_position     TEXT,
  user_organization TEXT,
  tel               TEXT,
  destination       TEXT,                    -- ขออนุญาตใช้รถยนต์ (ไปที่ไหน)
  objective         TEXT,                    -- เพื่อ (วัตถุประสงค์)
  passenger         INTEGER,
  note              TEXT,
  date_start        TEXT NOT NULL,
  date_finish       TEXT NOT NULL,
  time_start        TEXT,
  time_finish       TEXT,
  status            TEXT DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
  reject_reason     TEXT,
  driver_id         BIGINT REFERENCES drivers(id) ON DELETE SET NULL,
  -- Denormalised driver snapshot (filled on approve):
  driver_name       TEXT,
  driver_tel        TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────
-- 5. ROW LEVEL SECURITY
-- ──────────────────────────────────────────────────────────────
ALTER TABLE profiles  ENABLE ROW LEVEL SECURITY;
ALTER TABLE cars      ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers   ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION current_profile_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role
  FROM public.profiles
  WHERE id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION normalize_profile_role()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.role IS NULL OR NEW.role = '' OR NEW.role = 'member' THEN
    NEW.role := 'user';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION sync_profile_user_id()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.id IS NOT NULL AND NEW.user_id IS NULL THEN
    NEW.user_id := NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_normalize_role ON profiles;
CREATE TRIGGER profiles_normalize_role
  BEFORE INSERT OR UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION normalize_profile_role();

DROP TRIGGER IF EXISTS profiles_sync_user_id ON profiles;
CREATE TRIGGER profiles_sync_user_id
  BEFORE INSERT OR UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION sync_profile_user_id();

-- --- profiles ---
-- Users can read and update their own profile
CREATE POLICY "profiles_select_own"  ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own"  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own"  ON profiles FOR UPDATE USING (auth.uid() = id);
-- Admin can read all profiles
CREATE POLICY "profiles_select_admin" ON profiles FOR SELECT
  USING (current_profile_role() = 'admin');

-- --- cars ---
-- Any authenticated user can read cars
CREATE POLICY "cars_select_auth" ON cars FOR SELECT USING (auth.uid() IS NOT NULL);
-- Staff and admin can insert/update/delete
CREATE POLICY "cars_write_staff" ON cars FOR INSERT
  WITH CHECK (current_profile_role() IN ('admin', 'staff'));
CREATE POLICY "cars_update_staff" ON cars FOR UPDATE
  USING (current_profile_role() IN ('admin', 'staff'));
CREATE POLICY "cars_delete_admin" ON cars FOR DELETE
  USING (current_profile_role() = 'admin');

-- --- drivers ---
-- Any authenticated user can read drivers
CREATE POLICY "drivers_select_auth" ON drivers FOR SELECT USING (auth.uid() IS NOT NULL);
-- Staff and admin manage drivers
CREATE POLICY "drivers_write_staff" ON drivers FOR INSERT
  WITH CHECK (current_profile_role() IN ('admin', 'staff'));
CREATE POLICY "drivers_update_staff" ON drivers FOR UPDATE
  USING (current_profile_role() IN ('admin', 'staff'));
CREATE POLICY "drivers_delete_admin" ON drivers FOR DELETE
  USING (current_profile_role() = 'admin');

-- --- bookings ---
-- Users can see only their own bookings
CREATE POLICY "bookings_select_own" ON bookings FOR SELECT
  USING (user_id = auth.uid()::TEXT);
-- Staff and admin can see ALL bookings
CREATE POLICY "bookings_select_staff" ON bookings FOR SELECT
  USING (current_profile_role() IN ('admin', 'staff'));
-- Any authenticated user can create a booking
CREATE POLICY "bookings_insert_auth" ON bookings FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);
-- Staff and admin can update bookings (approve/reject/assign driver)
CREATE POLICY "bookings_update_staff" ON bookings FOR UPDATE
  USING (current_profile_role() IN ('admin', 'staff'))
  WITH CHECK (current_profile_role() IN ('admin', 'staff'));
-- Users can cancel only their own pending/approved bookings
CREATE POLICY "bookings_cancel_own" ON bookings FOR UPDATE
  USING (user_id = auth.uid()::TEXT AND status IN ('pending', 'approved'))
  WITH CHECK (user_id = auth.uid()::TEXT AND status = 'cancelled');
-- Admin can delete bookings
CREATE POLICY "bookings_delete_admin" ON bookings FOR DELETE
  USING (current_profile_role() = 'admin');

-- ──────────────────────────────────────────────────────────────
-- 6. MIGRATION HELPERS (run on existing db if upgrading)
-- ──────────────────────────────────────────────────────────────
-- Add destination column (Phase 1 migration):
-- ALTER TABLE bookings ADD COLUMN IF NOT EXISTS destination TEXT;
-- ALTER TABLE bookings ADD COLUMN IF NOT EXISTS car_id BIGINT;

-- Change user_id to TEXT (Phase 2 migration — WARNING: drops FK constraint):
-- ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_user_id_fkey;
-- ALTER TABLE bookings ALTER COLUMN user_id TYPE TEXT USING user_id::TEXT;

-- Add driver snapshot columns to bookings:
-- ALTER TABLE bookings ADD COLUMN IF NOT EXISTS driver_name TEXT;
-- ALTER TABLE bookings ADD COLUMN IF NOT EXISTS driver_tel  TEXT;

-- Add driver_id FK to cars:
-- ALTER TABLE cars ADD COLUMN IF NOT EXISTS driver_id BIGINT REFERENCES drivers(id) ON DELETE SET NULL;

-- ──────────────────────────────────────────────────────────────
-- 7. LEGACY USERS TABLE (kept for reference / data migration)
--    After migrating existing users to Supabase Auth + profiles,
--    this table can be archived or dropped.
-- ──────────────────────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS users (
--   id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   username     TEXT UNIQUE NOT NULL,
--   password     TEXT NOT NULL,
--   name         TEXT NOT NULL,
--   position     TEXT,
--   organization TEXT,
--   internal_tel TEXT NOT NULL,
--   mobile_tel   TEXT,
--   role         TEXT DEFAULT 'user',
--   created_at   TIMESTAMPTZ DEFAULT NOW()
-- );
