-- DriveSelect: repair core tables and RLS for the linked Supabase project.
-- Safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  position TEXT,
  organization TEXT,
  internal_tel TEXT,
  mobile_tel TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'staff', 'user')),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS id UUID;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS position TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS organization TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS internal_tel TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mobile_tel TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'profiles'
      AND column_name = 'username'
  ) THEN
    EXECUTE $sql$
      UPDATE public.profiles
      SET email = COALESCE(NULLIF(email, ''), NULLIF(username, '') || '@users.local')
      WHERE COALESCE(email, '') = ''
    $sql$;
  END IF;
END $$;

UPDATE public.profiles
SET
  name = COALESCE(NULLIF(name, ''), split_part(COALESCE(email, 'user@users.local'), '@', 1)),
  role = COALESCE(NULLIF(role, ''), 'user'),
  is_active = COALESCE(is_active, TRUE),
  created_at = COALESCE(created_at, NOW());

UPDATE public.profiles p
SET id = au.id
FROM auth.users au
WHERE p.id IS NULL
  AND p.email IS NOT NULL
  AND au.email = p.email;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_id_key ON public.profiles (id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'profiles'
      AND column_name = 'role'
  ) THEN
    ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_role_check
      CHECK (role IN ('admin', 'staff', 'user'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.drivers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tel TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS tel TEXT;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  image TEXT NOT NULL DEFAULT '',
  license_plate TEXT,
  seats INTEGER,
  available BOOLEAN DEFAULT TRUE,
  driver_id BIGINT REFERENCES public.drivers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS license_plate TEXT;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS seats INTEGER;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS available BOOLEAN DEFAULT TRUE;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS driver_id BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'cars_driver_id_fkey'
  ) THEN
    ALTER TABLE public.cars
      ADD CONSTRAINT cars_driver_id_fkey
      FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;
  END IF;
END $$;

UPDATE public.cars
SET
  image = COALESCE(image, ''),
  available = COALESCE(available, TRUE),
  created_at = COALESCE(created_at, NOW());

ALTER TABLE public.cars ALTER COLUMN image SET NOT NULL;

CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE NOT NULL,
  user_id TEXT,
  car_name TEXT NOT NULL,
  car_license TEXT,
  car_type TEXT,
  user_name TEXT NOT NULL,
  user_position TEXT,
  user_organization TEXT,
  tel TEXT,
  destination TEXT,
  objective TEXT,
  passenger INTEGER,
  note TEXT,
  date_start TEXT NOT NULL,
  date_finish TEXT NOT NULL,
  time_start TEXT,
  time_finish TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reject_reason TEXT,
  driver_id BIGINT REFERENCES public.drivers(id) ON DELETE SET NULL,
  driver_name TEXT,
  driver_tel TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS car_name TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS car_license TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS car_type TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_position TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_organization TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS tel TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS destination TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS passenger INTEGER;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS date_start TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS date_finish TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS time_start TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS time_finish TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS reject_reason TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS driver_id BIGINT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS driver_name TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS driver_tel TEXT;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_user_id_fkey;

DO $$
DECLARE
  policy_row RECORD;
BEGIN
  FOR policy_row IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'bookings'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.bookings', policy_row.policyname);
  END LOOP;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'bookings'
      AND column_name = 'user_id'
      AND data_type <> 'text'
  ) THEN
    ALTER TABLE public.bookings
      ALTER COLUMN user_id TYPE TEXT USING user_id::TEXT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'bookings_driver_id_fkey'
  ) THEN
    ALTER TABLE public.bookings
      ADD CONSTRAINT bookings_driver_id_fkey
      FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;
  END IF;
END $$;

UPDATE public.bookings
SET
  status = COALESCE(NULLIF(status, ''), 'pending'),
  created_at = COALESCE(created_at, NOW());

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'bookings'
      AND column_name = 'status'
  ) THEN
    ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_status_check;
    ALTER TABLE public.bookings
      ADD CONSTRAINT bookings_status_check
      CHECK (status IN ('pending', 'approved', 'rejected'));
  END IF;
END $$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON public.profiles;
DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
DROP POLICY IF EXISTS profiles_select_admin ON public.profiles;

CREATE POLICY profiles_select_own
  ON public.profiles
  FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY profiles_update_own
  ON public.profiles
  FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY profiles_select_admin
  ON public.profiles
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

DROP POLICY IF EXISTS cars_select_auth ON public.cars;
DROP POLICY IF EXISTS cars_write_staff ON public.cars;
DROP POLICY IF EXISTS cars_update_staff ON public.cars;
DROP POLICY IF EXISTS cars_delete_admin ON public.cars;

CREATE POLICY cars_select_auth
  ON public.cars
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY cars_write_staff
  ON public.cars
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY cars_update_staff
  ON public.cars
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY cars_delete_admin
  ON public.cars
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

DROP POLICY IF EXISTS drivers_select_auth ON public.drivers;
DROP POLICY IF EXISTS drivers_write_staff ON public.drivers;
DROP POLICY IF EXISTS drivers_update_staff ON public.drivers;
DROP POLICY IF EXISTS drivers_delete_admin ON public.drivers;

CREATE POLICY drivers_select_auth
  ON public.drivers
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY drivers_write_staff
  ON public.drivers
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY drivers_update_staff
  ON public.drivers
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY drivers_delete_admin
  ON public.drivers
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

DROP POLICY IF EXISTS bookings_select_own ON public.bookings;
DROP POLICY IF EXISTS bookings_select_staff ON public.bookings;
DROP POLICY IF EXISTS bookings_insert_auth ON public.bookings;
DROP POLICY IF EXISTS bookings_update_staff ON public.bookings;
DROP POLICY IF EXISTS bookings_delete_admin ON public.bookings;

CREATE POLICY bookings_select_own
  ON public.bookings
  FOR SELECT
  USING (user_id = auth.uid()::TEXT);

CREATE POLICY bookings_select_staff
  ON public.bookings
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY bookings_insert_auth
  ON public.bookings
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY bookings_update_staff
  ON public.bookings
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin', 'staff')
    )
  );

CREATE POLICY bookings_delete_admin
  ON public.bookings
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

COMMIT;
